### ISSUE TITLE
Store.checkpoint_states should be updated when justified_checkpoint updated

### ISSUE THREAD

**Issue by ericsson49** [ethereum/eth2.0-specs#1887]
`store_target_checkpoint_state` is called to update `checkpoint_states` during `on_attestation` processing.
However, it's not updated during `on_block` processing, if a block results in a newer justified_checkpont.
Which may result in an `KeyError` during `get_head` call. For example,
```python
from eth2spec.utils import bls
bls.bls_active = False

from eth2spec.phase0 import spec

configs_path = 'configs/'
from eth2spec.config import config_util
from importlib import reload
config_util.prepare_config(configs_path, 'minimal')
reload(spec)

from eth2spec.test.helpers.deposits import prepare_genesis_deposits
from eth2spec.test.helpers.keys import pubkey_to_privkey

eth1_block_hash=b'\x42' * 32
eth1_timestamp=spec.MIN_GENESIS_TIME
deposit_count = 16
deposits, deposit_root, _ = prepare_genesis_deposits(spec, deposit_count, spec.MAX_EFFECTIVE_BALANCE, signed=True)
genesis_state = spec.initialize_beacon_state_from_eth1(eth1_block_hash, eth1_timestamp, deposits)

store = spec.get_forkchoice_store(genesis_state)

def set_slot(slot):
    spec.on_tick(store, store.genesis_time+spec.SECONDS_PER_SLOT*slot)

def mk_block(slot,head,atts):
    head_state = store.block_states[head].copy()
    if head_state.slot < slot-1:
        spec.process_slots(head_state, slot-1)
    state = head_state.copy()
    spec.process_slots(state, slot)

    proposer = spec.get_beacon_proposer_index(state)
    SK = pubkey_to_privkey[state.validators[proposer].pubkey]
    randao_reveal = spec.get_epoch_signature(state, spec.BeaconBlock(slot=slot), SK)
    eth1vote = spec.get_eth1_vote(state, [])
    block = spec.BeaconBlock(
        slot=slot, proposer_index=proposer, parent_root=head,
        body=spec.BeaconBlockBody(attestations=atts, eth1_data=eth1vote))
    block.state_root = spec.compute_new_state_root(head_state.copy(), block)
    block_signature = spec.get_block_signature(state, block, SK)
    return spec.SignedBeaconBlock(message=block, signature=block_signature)

def mk_atts(slot, head):
    head_state = store.block_states[head].copy()
    if head_state.slot < int(slot)-1:
        spec.process_slots(head_state, slot-1)
    state = head_state.copy()
    if state.slot < slot:
        spec.process_slots(state, slot)
    
    src = state.current_justified_checkpoint
    start_slot = spec.compute_start_slot_at_epoch(spec.get_current_epoch(state))
    epoch_boundary_block_root = head if start_slot == state.slot else spec.get_block_root_at_slot(state, start_slot)
    target_chkpt = spec.Checkpoint(epoch=spec.get_current_epoch(state), root=epoch_boundary_block_root)
    atts = []
    committee_count = spec.get_committee_count_at_slot(state, slot)
    for index in range(committee_count):
        data = spec.AttestationData(slot=slot, index=index, beacon_block_root=head,
            source=state.current_justified_checkpoint,
            target=target_chkpt)
        committee = spec.get_beacon_committee(state, slot, index)
        for i in range(len(committee)):
            bits = spec.Bitlist[spec.MAX_VALIDATORS_PER_COMMITTEE]([0] * len(committee))
            bits[i] = 1
            att_sig = spec.get_attestation_signature(state, data,
                    pubkey_to_privkey[state.validators[committee[i]].pubkey])
            atts.append(spec.Attestation(aggregation_bits=bits, data=data, signature=att_sig))
    return atts

def do_step():
    slot = spec.get_current_slot(store)
    head = spec.get_head(store)
    atts = mk_atts(slot, head)
    slot = slot + 1
    set_slot(slot)
    #for a in atts:
    #    spec.on_attestation(store, a)
    b = mk_block(slot, head, atts)
    spec.on_block(store, b)

for i in range(spec.SLOTS_PER_EPOCH * 3):
    do_step()

spec.get_head(store)
```

```
Traceback (most recent call last):
  File "testcase1.py", line 85, in <module>
    spec.get_head(store)
  File "/mnt/c/Users/ericsson/IdeaProjects/tmp/eth2.0-specs_v0.11.3/venv/lib/python3.8/site-packages/eth2spec/phase0/spec.py", line 1392, in get_head
    head = max(children, key=lambda root: (get_latest_attesting_balance(store, root), root))
  File "/mnt/c/Users/ericsson/IdeaProjects/tmp/eth2.0-specs_v0.11.3/venv/lib/python3.8/site-packages/eth2spec/phase0/spec.py", line 1392, in <lambda>
    head = max(children, key=lambda root: (get_latest_attesting_balance(store, root), root))
  File "/mnt/c/Users/ericsson/IdeaProjects/tmp/eth2.0-specs_v0.11.3/venv/lib/python3.8/site-packages/eth2spec/phase0/spec.py", line 1322, in get_latest_attesting_balance
    state = store.checkpoint_states[store.justified_checkpoint]
KeyError: Checkpoint(Container)
    epoch: Epoch = 2
    root: Root = 0x622549f0ce5a668ebaac0e752cf638d673f8e92fa0a6d0478656fa76a53a02b8
```

**Comment by ericsson49** [comment]
reproduced in both `dev` and 'v0.13.1`

**Comment by adiasg** [comment]
@ericsson49 Great catch!

**Cause of issue:** `on_attestation` is never applied to new un-seen attestations in `block.message.body.attestations` in `on_block`. 

The [intention was to run `on_attestation` for those attestations](https://github.com/ethereum/eth2.0-specs/blame/117fb12888add6911c8dcda8c9313e72ee0b3ff9/specs/core/0_fork-choice.md#L242), but the code is missing :sweat_smile: 

**Solution of issue:** Run `on_attestation` on new un-seen attestations in `on_block`.

**Comment by ericsson49** [comment]
I have been expecting that clients are to extract `block.message.body.attestations`, however, there is no indication/requirement that this should be done before processing the block (calling `on_block(store, block)`.

Such a requirement is reasonable, of course, however, my worry is that then there may arise tricky cases with invalid/early/etc blocks and/or invalid/early/etc attestations inside blocks. Such cases can be resolved, however, processing blocks and attestations as separate pieces (e.g. in separate transactions) is much easier conceptually. While, if there are partial ordering requirements then it may be somewhat complicated.

**Comment by djrtwo** [comment]
The intention of the fork choice is to certainly add any attestations you get from any location whether it be directly from an attestation gossip topic, from within a block, or even hand delivered by fedex

Open to a suggestion on how to make that clearer in the "spec". I don't think we need to enumerate attestations from blocks in code but some more directive text might be warranted.

Closing for now, but will entertain PRs with clarifying text
