### ISSUE TITLE
Type error in `process_custody_game_operations` when invoking `process_chuck_challenge`

### ISSUE THREAD

**Issue by ericsson49** [ethereum/eth2.0-specs#1908]
[process_custody_game_operations](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase1/custody-game.md#custody-game-operations) applies [process_chunk_challenge](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase1/custody-game.md#chunk-challenges) for elements of `body.chunk_challenges` and `body.chunk_challenge_responses` lists.

However, there is a typing error, since the `process_custody_game_operations` expects that its second parameter has type `CustodyChunkChallenge`, while both `BeaconBlockBody.chunk_challenges` and
`BeaconBlockBody.chunk_challenges` have type `List[CustodyChunkResponse, MAX_CUSTODY_CHUNK_CHALLENGES]`

Here is a test snippet illustrating the problem
```python
from eth2spec.phase1 import spec

state = spec.BeaconState()
body = spec.BeaconBlockBody(chunk_challenges=[spec.CustodyChunkResponse()])
spec.process_custody_game_operations(state, body)
```

Stack trace
```
Traceback (most recent call last):
  File "/mnt/c/Users/ericsson/IdeaProjects/eth2.0-specs/venv/lib/python3.8/site-packages/remerkleable/complex.py", line 781, in __getattr__
    i = self.__class__._field_indices[item]
KeyError: 'attestation'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/ericsson/IdeaProjects/eth2.0-specs/venv/lib/python3.8/site-packages/eth2spec/phase1/spec.py", line 2128, in process_custody_game_operations
    for_ops(body.chunk_challenges, process_chunk_challenge)
  File "/mnt/c/Users/ericsson/IdeaProjects/eth2.0-specs/venv/lib/python3.8/site-packages/eth2spec/phase1/spec.py", line 2126, in for_ops
    fn(state, operation)
  File "/mnt/c/Users/ericsson/IdeaProjects/eth2.0-specs/venv/lib/python3.8/site-packages/eth2spec/phase1/spec.py", line 2137, in process_chunk_challenge
    assert is_valid_indexed_attestation(state, get_indexed_attestation(state, challenge.attestation))
  File "/mnt/c/Users/ericsson/IdeaProjects/eth2.0-specs/venv/lib/python3.8/site-packages/remerkleable/complex.py", line 783, in __getattr__
    raise AttributeError(f"unknown attribute {item}")
AttributeError: unknown attribute attestation
```

**Comment by hwwhww** [comment]
closing via #1909, thanks @ericsson49!
